/* =========================================================
   HINDI TRANSLATIONS — "English text": "हिन्दी पाठ"
   The English text on the left must match the page exactly.
   Anything not listed here simply stays in English.
   ========================================================= */
window.LANG_HI = {
  "Home": "होम",
  "About Us": "हमारे बारे में",
  "Tour": "टूर",
  "Attractions": "आकर्षण",
  "Traveller Zone": "यात्री ज़ोन",
  "Contact us": "संपर्क करें",
  "Book Now": "अभी बुक करें",
  "Main menu": "मुख्य मेनू",
  "Open menu": "मेनू खोलें",
  "Close menu": "मेनू बंद करें",
  "Language": "भाषा",
  "Choose destination": "गंतव्य चुनें",
  "Call us": "हमें कॉल करें",
  "WhatsApp us": "हमें व्हाट्सऐप करें",

  "Planning a Cambodia trip?": "कंबोडिया यात्रा की योजना बना रहे हैं?",
  "Get travel tips, seat availability and seasonal offers on the Angkor Wat package — straight to your inbox.": "अंगकोर वाट पैकेज के यात्रा सुझाव, सीटों की उपलब्धता और मौसमी ऑफ़र — सीधे अपने इनबॉक्स में पाएँ।",
  "Email address": "ईमेल पता",
  "Your email address": "आपका ईमेल पता",
  "Subscribe": "सब्सक्राइब करें",
  "A single-country travel agency built around one trip we know well — Angkor Wat, Cambodia. Air, visa, stay and an Indian-speaking escort, handled end to end.": "एक ही देश पर केंद्रित ट्रैवल एजेंसी, जो उस एक यात्रा के लिए बनी है जिसे हम अच्छी तरह जानते हैं — अंगकोर वाट, कंबोडिया। हवाई टिकट, वीज़ा, ठहरना और भारतीय भाषा बोलने वाला एस्कॉर्ट — शुरू से अंत तक सब हमारी ज़िम्मेदारी।",
  "Explore": "एक्सप्लोर करें",
  "Temples Covered": "शामिल मंदिर",
  "Ta Prohm": "ता प्रोम",
  "Angkor Thom": "अंगकोर थॉम",
  "Banteay Srei": "बांतेय स्रेई",
  "Preah Khan": "प्रेह खान",
  "Get In Touch": "संपर्क में रहें",
  "All rights reserved.": "सर्वाधिकार सुरक्षित।",

  "Thank you — you're subscribed.": "धन्यवाद — आप सब्सक्राइब हो गए हैं।",
  "Thank you! We'll call you back with dates and pricing.": "धन्यवाद! हम तारीख़ों और कीमत के साथ आपको कॉल करेंगे।",
  "Couldn't send right now. Please WhatsApp us on {phone}.": "अभी भेजा नहीं जा सका। कृपया हमें {phone} पर व्हाट्सऐप करें।",
  "Opening WhatsApp with your details — just press send.": "आपकी जानकारी के साथ व्हाट्सऐप खुल रहा है — बस सेंड दबाएँ।",
  "Sending…": "भेजा जा रहा है…",

  "Page not found | AngkorIndianTrip": "पेज नहीं मिला | AngkorIndianTrip",
  "Page not found": "पेज नहीं मिला",
  "This page wandered off into the jungle.": "यह पेज जंगल में कहीं भटक गया है।",
  "The link may be old or mistyped. Head back home and start again.": "हो सकता है लिंक पुराना हो या ग़लत टाइप हुआ हो। होम पेज पर लौटकर फिर से शुरू करें।",
  "Back to Home": "होम पर वापस जाएँ",

  "About Us — One Country, One Trip | AngkorIndianTrip": "हमारे बारे में — एक देश, एक यात्रा | AngkorIndianTrip",
  "One country. One trip. Done properly.": "एक देश। एक यात्रा। पूरी तरह सही ढंग से।",
  "AngkorIndianTrip runs a single package — Angkor Wat, Cambodia — and puts everything into getting that one trip right, instead of spreading thin across destinations.": "AngkorIndianTrip सिर्फ़ एक पैकेज चलाता है — अंगकोर वाट, कंबोडिया — और कई गंतव्यों में बँटने के बजाय उसी एक यात्रा को बेहतरीन बनाने में पूरी मेहनत लगाता है।",
  "Our Story": "हमारी कहानी",
  "Why we chose to focus on just Angkor Wat": "हमने सिर्फ़ अंगकोर वाट पर ध्यान देना क्यों चुना",
  "Most travel agencies list dozens of countries. We picked one — Cambodia’s Angkor Wat — and built our entire operation around it: the flights, the visa paperwork, the local guides, the hotel tie-ups, and an Indian-speaking escort who travels with every group.": "ज़्यादातर ट्रैवल एजेंसियाँ दर्जनों देशों की सूची देती हैं। हमने एक चुना — कंबोडिया का अंगकोर वाट — और अपना पूरा काम उसी के इर्द-गिर्द खड़ा किया: उड़ानें, वीज़ा की काग़ज़ी कार्रवाई, स्थानीय गाइड, होटलों से तालमेल और भारतीय भाषा बोलने वाला एस्कॉर्ट जो हर समूह के साथ चलता है।",
  "That focus means fewer surprises. We know which mornings give you the temple to yourself, which routes avoid the midday heat, and which small details — a missed visa document, a late transfer — usually go wrong elsewhere. We’ve built the trip so they don’t.": "इसी फ़ोकस की वजह से अनचाही परेशानियाँ कम होती हैं। हमें पता है कि किस सुबह मंदिर में भीड़ नहीं होती, कौन-से रास्ते दोपहर की गर्मी से बचाते हैं, और कौन-सी छोटी बातें — छूटा हुआ वीज़ा दस्तावेज़, देर से पहुँची गाड़ी — अक्सर दूसरी जगह गड़बड़ कर देती हैं। हमने यात्रा ऐसे बनाई है कि ऐसा न हो।",
  "We’re based in Cambodia, and every enquiry is handled directly by our team — not passed between call centres.": "हम कंबोडिया में ही स्थित हैं, और हर पूछताछ सीधे हमारी टीम सँभालती है — कॉल सेंटरों के बीच नहीं घुमाई जाती।",
  "What We Believe": "हमारा विश्वास",
  "The way we run this trip": "हम यह यात्रा कैसे चलाते हैं",
  "Depth over spread": "फैलाव नहीं, गहराई",
  "One destination, done thoroughly — not a generic multi-country itinerary.": "एक गंतव्य, पूरी गहराई से — कोई आम बहु-देशीय यात्रा-कार्यक्रम नहीं।",
  "An escort, not just a guide": "सिर्फ़ गाइड नहीं, एक एस्कॉर्ट",
  "An Indian-speaking escort stays with your group from arrival to departure.": "भारतीय भाषा बोलने वाला एस्कॉर्ट आगमन से प्रस्थान तक आपके समूह के साथ रहता है।",
  "Transparent pricing": "पारदर्शी कीमत",
  "Air ticket and visa are quoted upfront, in the package — no add-on surprises.": "हवाई टिकट और वीज़ा की कीमत पैकेज में पहले ही बता दी जाती है — बाद में कोई अतिरिक्त ख़र्च नहीं।",
  "Reachable, always": "हमेशा उपलब्ध",
  "24/7 support during your trip — a real person, not a ticket queue.": "यात्रा के दौरान 24/7 सहायता — एक असली इंसान, कोई टिकट कतार नहीं।",
  "How It Works": "यह कैसे काम करता है",
  "From enquiry to Angkor Wat": "पूछताछ से अंगकोर वाट तक",
  "Tell us your dates": "हमें अपनी तारीख़ें बताएँ",
  "Call, WhatsApp, or fill the enquiry form — we'll check flight and visa timelines for you.": "कॉल करें, व्हाट्सऐप करें या पूछताछ फ़ॉर्म भरें — हम आपके लिए उड़ान और वीज़ा की समय-सीमा देख लेंगे।",
  "We lock the plan": "हम योजना पक्की करते हैं",
  "Air ticket, visa, hotel and the 3-day route are confirmed and shared before you pay in full.": "पूरा भुगतान करने से पहले हवाई टिकट, वीज़ा, होटल और 3 दिन का रूट कन्फ़र्म करके आपसे साझा किया जाता है।",
  "Travel with an escort": "एस्कॉर्ट के साथ यात्रा करें",
  "From Siem Reap arrival to the Big Circle on day three, someone from our team is with you.": "सिएम रीप पहुँचने से लेकर तीसरे दिन के बिग सर्कल तक, हमारी टीम का कोई सदस्य आपके साथ रहता है।",
  "Ready to see Angkor Wat yourself?": "ख़ुद अंगकोर वाट देखने के लिए तैयार हैं?",
  "Tell us your travel month and group size — we’ll send dates, pricing and visa timelines the same day.": "हमें अपनी यात्रा का महीना और समूह का आकार बताएँ — हम उसी दिन तारीख़ें, कीमत और वीज़ा की समय-सीमा भेज देंगे।",
  "Enquire Now": "अभी पूछताछ करें",

  "Angkor Wat Attractions — What's Covered | AngkorIndianTrip": "अंगकोर वाट के आकर्षण — क्या-क्या शामिल है | AngkorIndianTrip",
  "Angkor Wat Attractions": "अंगकोर वाट के आकर्षण",
  "Every temple, site and experience covered on the 3-day Angkor Wat package — grouped by the day you’ll visit them.": "3 दिन के अंगकोर वाट पैकेज में शामिल हर मंदिर, स्थल और अनुभव — जिस दिन आप उन्हें देखेंगे, उसी के अनुसार।",
  "List of Attractions": "आकर्षणों की सूची",
  "What's covered on this tour": "इस टूर में क्या-क्या शामिल है",
  "Day 1": "दिन 1",
  "Day 2": "दिन 2",
  "Day 3": "दिन 3",
  "Day 2–3": "दिन 2–3",
  "Floating Village": "तैरता गाँव",
  "A community built on the water, reached by boat — one of the first stops after you land in Siem Reap.": "पानी पर बसी एक बस्ती, जहाँ नाव से पहुँचा जाता है — सिएम रीप उतरने के बाद के पहले पड़ावों में से एक।",
  "Kulen Mountain Waterfall": "कुलेन पर्वत झरना",
  "A jungle waterfall on Cambodia's most sacred mountain, a short drive from Siem Reap.": "कंबोडिया के सबसे पवित्र पर्वत पर जंगल के बीच एक झरना, सिएम रीप से थोड़ी ही दूरी पर।",
  "Apsara Dance Show & Dinner": "अप्सरा नृत्य शो और रात्रिभोज",
  "A traditional Khmer dance performance over dinner, closing out arrival day.": "रात्रिभोज के साथ पारंपरिक ख्मेर नृत्य प्रस्तुति, जिससे आगमन का दिन पूरा होता है।",
  "Angkor Wat Temple": "अंगकोर वाट मंदिर",
  "The centrepiece of the trip — the largest religious monument in the world, built for Vishnu.": "यात्रा का मुख्य आकर्षण — दुनिया का सबसे बड़ा धार्मिक स्मारक, जो भगवान विष्णु के लिए बनाया गया था।",
  "Banteay Kdei Temple": "बांतेय कदेई मंदिर",
  "A quieter Buddhist monastery temple, part of the main Angkor circuit.": "एक शांत बौद्ध मठ-मंदिर, जो मुख्य अंगकोर सर्किट का हिस्सा है।",
  "Angkor Thom City": "अंगकोर थॉम नगर",
  "The fortified last capital of the Khmer empire, entered through its famous carved gates.": "ख्मेर साम्राज्य की क़िलेबंद अंतिम राजधानी, जिसमें इसके प्रसिद्ध नक्काशीदार द्वारों से प्रवेश किया जाता है।",
  "Ta Keo Temple": "ता केओ मंदिर",
  "A steep, mostly-undecorated temple-mountain — one of Angkor's earliest sandstone builds.": "एक खड़ी चढ़ाई वाला, लगभग बिना सजावट का पर्वत-मंदिर — अंगकोर की सबसे शुरुआती बलुआ पत्थर की इमारतों में से एक।",
  "Ta Prohm Temple": "ता प्रोम मंदिर",
  "The \"Tomb Raider\" temple — left half-swallowed by jungle roots, largely as it was found.": "\"टूम्ब रेडर\" वाला मंदिर — जंगल की जड़ों में आधा समाया हुआ, लगभग वैसा ही जैसा यह मिला था।",
  "Banteay Srei (Pink Temple)": "बांतेय स्रेई (गुलाबी मंदिर)",
  "A small, intricately carved pink sandstone temple, 40km out on the Big Circle.": "गुलाबी बलुआ पत्थर का छोटा, बारीक नक्काशी वाला मंदिर, बिग सर्कल पर 40 किमी दूर।",
  "East Mebon Temple": "ईस्ट मेबोन मंदिर",
  "A temple-mountain once set on an island in a now-dry reservoir, guarded by stone elephants.": "एक पर्वत-मंदिर जो कभी अब सूख चुके जलाशय के बीच टापू पर था, जिसकी रखवाली पत्थर के हाथी करते हैं।",
  "Preah Khan Temple": "प्रेह खान मंदिर",
  "A sprawling, atmospheric complex — once a Buddhist university and city.": "एक विशाल, मनमोहक परिसर — जो कभी बौद्ध विश्वविद्यालय और नगर था।",
  "Ta Som Temple": "ता सोम मंदिर",
  "A small, little-visited temple known for the tree growing through its eastern gate.": "एक छोटा, कम भीड़ वाला मंदिर, जो अपने पूर्वी द्वार से उगते पेड़ के लिए जाना जाता है।",
  "Pre Rup Temple": "प्रे रूप मंदिर",
  "A striking brick-and-sandstone temple-mountain, a favourite for late-afternoon light.": "ईंट और बलुआ पत्थर का शानदार पर्वत-मंदिर, ढलती दोपहर की रोशनी में देखने के लिए पसंदीदा।",
  "Neak Pean Temple": "नेक पेन मंदिर",
  "A small temple on an artificial island, reached by a raised wooden walkway.": "कृत्रिम टापू पर बना छोटा मंदिर, जहाँ लकड़ी के ऊँचे पुल से पहुँचा जाता है।",
  "Photo Gallery": "फ़ोटो गैलरी",
  "More from Angkor": "अंगकोर की और झलकियाँ",
  "Video of Angkor Wat at sunrise": "सूर्योदय के समय अंगकोर वाट का वीडियो",
  "Getting Around": "घूमने के साधन",
  "Mode of transport": "परिवहन के साधन",
  "VIP Car": "वीआईपी कार",
  "A private air-conditioned sedan for small groups who want a quieter, more comfortable ride between temples.": "छोटे समूहों के लिए निजी वातानुकूलित सेडान, जो मंदिरों के बीच शांत और ज़्यादा आरामदायक सफ़र चाहते हैं।",
  "Non-VIP Car": "नॉन-वीआईपी कार",
  "A standard air-conditioned car — the practical, budget-friendly option for couples and small families.": "एक सामान्य वातानुकूलित कार — जोड़ों और छोटे परिवारों के लिए व्यावहारिक और किफ़ायती विकल्प।",
  "Minibus": "मिनीबस",
  "For larger groups travelling together — one vehicle, one driver, everyone on the same schedule.": "साथ यात्रा करने वाले बड़े समूहों के लिए — एक वाहन, एक ड्राइवर, सब एक ही समय-सारणी पर।",
  "Angkor Tuk-Tuk": "अंगकोर टुक-टुक",
  "The classic way to see the temples — open-air, unhurried, and easy to hop in and out of between stops.": "मंदिर देखने का पारंपरिक तरीक़ा — खुली हवा में, आराम से, और पड़ावों के बीच चढ़ना-उतरना आसान।",
  "Want the full list explained day by day?": "पूरी सूची दिन-ब-दिन समझना चाहते हैं?",
  "See how these sites fit into the 3-day itinerary, or ask us for a callback.": "देखें कि ये स्थल 3 दिन के कार्यक्रम में कैसे शामिल हैं, या हमसे कॉलबैक माँगें।",
  "See Full Itinerary": "पूरा कार्यक्रम देखें",
  "Request Callback": "कॉलबैक माँगें",

  "Contact Us — Plan Your Angkor Wat Trip | AngkorIndianTrip": "संपर्क करें — अपनी अंगकोर वाट यात्रा की योजना बनाएँ | AngkorIndianTrip",
  "Let's plan your Angkor Wat trip": "आइए, आपकी अंगकोर वाट यात्रा की योजना बनाएँ",
  "Call, WhatsApp, or send an enquiry — a real person from our team will get back to you the same day.": "कॉल करें, व्हाट्सऐप करें या पूछताछ भेजें — हमारी टीम का कोई सदस्य उसी दिन आपसे संपर्क करेगा।",
  "Call Us": "हमें कॉल करें",
  "Mon–Sat, 10am–7pm IST": "सोम–शनि, सुबह 10 – शाम 7 बजे (भारतीय समय)",
  "Email Us": "हमें ईमेल करें",
  "We reply within one business day": "हम एक कार्यदिवस के भीतर जवाब देते हैं",
  "WhatsApp": "व्हाट्सऐप",
  "Fastest way to reach us": "हम तक पहुँचने का सबसे तेज़ तरीक़ा",
  "Chat on WhatsApp": "व्हाट्सऐप पर चैट करें",
  "Visit Us": "हमसे मिलें",
  "Our office": "हमारा कार्यालय",
  "Office location map": "कार्यालय का नक़्शा",
  "Office Hours": "कार्यालय का समय",
  "Monday – Saturday": "सोमवार – शनिवार",
  "10:00 AM – 7:00 PM": "सुबह 10:00 – शाम 7:00",
  "Sunday": "रविवार",
  "Closed": "बंद",
  "During your trip": "आपकी यात्रा के दौरान",
  "24/7 escort support": "24/7 एस्कॉर्ट सहायता",
  "Enquiry": "पूछताछ",
  "Send an enquiry": "पूछताछ भेजें",
  "Tell us your travel month and group size — we'll reply with dates, pricing and visa timelines.": "हमें अपनी यात्रा का महीना और समूह का आकार बताएँ — हम तारीख़ों, कीमत और वीज़ा की समय-सीमा के साथ जवाब देंगे।",
  "Full name": "पूरा नाम",
  "Phone number": "फ़ोन नंबर",
  "Email": "ईमेल",
  "Preferred travel month": "यात्रा का पसंदीदा महीना",
  "Select a month": "महीना चुनें",
  "January": "जनवरी",
  "February": "फ़रवरी",
  "March": "मार्च",
  "April": "अप्रैल",
  "May": "मई",
  "June": "जून",
  "July": "जुलाई",
  "August": "अगस्त",
  "September": "सितंबर",
  "October": "अक्टूबर",
  "November": "नवंबर",
  "December": "दिसंबर",
  "Number of travellers": "यात्रियों की संख्या",
  "Message": "संदेश",
  "Send Enquiry": "पूछताछ भेजें",
  "Quick Answers": "त्वरित उत्तर",
  "Frequently asked questions": "अक्सर पूछे जाने वाले प्रश्न",
  "Is the Cambodia visa included in the package?": "क्या कंबोडिया का वीज़ा पैकेज में शामिल है?",
  "Yes — visa and air ticket are both bundled into the Angkor Wat package, as listed on the": "हाँ — वीज़ा और हवाई टिकट दोनों अंगकोर वाट पैकेज में शामिल हैं। पूरी जानकारी के लिए देखें:",
  "Tour page": "टूर पेज",
  "How many days is the tour?": "टूर कितने दिनों का है?",
  "2 nights / 3 days in Siem Reap, covering the main Angkor circuit on day two and the Big Circle on day three.": "सिएम रीप में 2 रातें / 3 दिन — दूसरे दिन मुख्य अंगकोर सर्किट और तीसरे दिन बिग सर्कल।",
  "Do you provide an escort for the whole trip?": "क्या आप पूरी यात्रा के लिए एस्कॉर्ट देते हैं?",
  "Yes, an Indian-speaking escort travels with your group from arrival to departure, with 24/7 support.": "हाँ, भारतीय भाषा बोलने वाला एस्कॉर्ट आगमन से प्रस्थान तक आपके समूह के साथ रहता है, 24/7 सहायता के साथ।",
  "Can I customise the itinerary or extend my stay?": "क्या मैं कार्यक्रम बदल सकता हूँ या ज़्यादा दिन रुक सकता हूँ?",
  "Yes — call or WhatsApp us with what you have in mind and we’ll check what’s possible.": "हाँ — आप जो चाहते हैं वह हमें कॉल या व्हाट्सऐप पर बताएँ, हम देखेंगे कि क्या-क्या संभव है।",
  "How do I confirm my booking?": "मैं अपनी बुकिंग कैसे कन्फ़र्म करूँ?",
  "Share your travel dates and group size through this page, by phone, or WhatsApp — we’ll confirm availability and the advance payment needed.": "इस पेज, फ़ोन या व्हाट्सऐप के ज़रिए अपनी यात्रा की तारीख़ें और समूह का आकार बताएँ — हम उपलब्धता और ज़रूरी अग्रिम भुगतान की पुष्टि कर देंगे।",

  "Angkor Wat Tour Package from India | AngkorIndianTrip": "भारत से अंगकोर वाट टूर पैकेज | AngkorIndianTrip",
  "Uncover. Discover.": "खोजें. जानें.",
  "Angkor Wat,": "अंगकोर वाट,",
  "Angkor Wat": "अंगकोर वाट",
  "Cambodia": "कंबोडिया",
  "Three days through temples that watched an empire rise — with a forgotten bond to India through Lord Vishnu, and everything handled for you.": "उन मंदिरों के बीच तीन दिन, जिन्होंने एक साम्राज्य को उभरते देखा — भगवान विष्णु के ज़रिए भारत से जुड़ा एक भूला-बिसरा रिश्ता, और सारी व्यवस्था हमारी।",
  "The Royal Capital.": "शाही राजधानी.",
  "Phnom Penh,": "नोम पेन्ह,",
  "Phnom Penh": "नोम पेन्ह",
  "Golden spires of the Royal Palace, wide riverside boulevards and the Independence Monument — Cambodia's capital, where the kingdom's story is still being written.": "रॉयल पैलेस के सुनहरे शिखर, नदी किनारे की चौड़ी सड़कें और स्वतंत्रता स्मारक — कंबोडिया की राजधानी, जहाँ इस राज्य की कहानी आज भी लिखी जा रही है।",
  "Independence Monument": "स्वतंत्रता स्मारक",
  "Capital landmark": "राजधानी की पहचान",
  "Quiet Coast.": "शांत समुद्र तट.",
  "Kep": "केप",
  "Province": "प्रांत",
  "A sleepy seaside province of green hills, a palm-lined beach and fresh crab straight off the boats — Cambodia at its most unhurried.": "हरी पहाड़ियों, ताड़ के पेड़ों से सजे समुद्र तट और नावों से सीधे आए ताज़ा केकड़ों वाला एक शांत समुद्री प्रांत — कंबोडिया का सबसे सुकून भरा रूप।",
  "Kep Beach": "केप बीच",
  "Seaside escape": "समुद्र किनारे सुकून",
  "Island Blues.": "नीले द्वीप.",
  "Sihanoukville": "सिहानोकविल",
  "White-sand bays, wooden jetties and clear turquoise water — the coast where Cambodia's islands begin.": "सफ़ेद रेत की खाड़ियाँ, लकड़ी की जेट्टियाँ और साफ़ फ़िरोज़ी पानी — वह तट जहाँ से कंबोडिया के द्वीप शुरू होते हैं।",
  "Island jetty": "द्वीप की जेट्टी",
  "Turquoise bays": "फ़िरोज़ी खाड़ियाँ",
  "Call an expert": "विशेषज्ञ से बात करें",
  "Air+Visa": "हवाई टिकट+वीज़ा",
  "Included": "शामिल",
  "Indian Support": "भारतीय सहायता",
  "Escort": "एस्कॉर्ट",
  "Throughout": "पूरी यात्रा में",
  "Siem Reap": "सिएम रीप",
  "Angkor Wat, Day 2": "अंगकोर वाट, दिन 2",
  "Full-day temple pass": "पूरे दिन का मंदिर पास",
  "Top Stops": "प्रमुख पड़ाव",
  "Where in Angkor do you want to go?": "अंगकोर में आप कहाँ जाना चाहते हैं?",
  "Filter stops": "पड़ाव फ़िल्टर करें",
  "All": "सभी",
  "Temples": "मंदिर",
  "Culture": "संस्कृति",
  "Nature": "प्रकृति",
  "Food": "खान-पान",
  "Bayon Temple": "बेयोन मंदिर",
  "Banteay Srei Temple": "बांतेय स्रेई मंदिर",
  "Angkor National Museum": "अंगकोर राष्ट्रीय संग्रहालय",
  "On request": "अनुरोध पर",
  "Apsara Dance Show": "अप्सरा नृत्य शो",
  "Kampong Phluk Floating Village": "काम्पोंग फ्लुक तैरता गाँव",
  "Cambodian Cultural Village": "कंबोडियाई सांस्कृतिक गाँव",
  "Old Market (Phsar Chas)": "पुराना बाज़ार (प्सार चास)",
  "Free time": "खाली समय",
  "Tonlé Sap Lake": "टोनले साप झील",
  "Kbal Spean River of Thousand Lingas": "कबाल स्पीन — हज़ार शिवलिंगों की नदी",
  "Kulen Mountain": "कुलेन पर्वत",
  "Angkor Archaeological Park Forest": "अंगकोर पुरातात्विक उद्यान का वन",
  "Prek Toal Bird Sanctuary": "प्रेक तोआल पक्षी अभयारण्य",
  "Pub Street": "पब स्ट्रीट",
  "Old Market Food Street": "पुराने बाज़ार की फ़ूड स्ट्रीट",
  "Made in Cambodia Market": "मेड इन कंबोडिया मार्केट",
  "Wat Bo Road Restaurants": "वाट बो रोड के रेस्तराँ",
  "Siem Reap Night Market": "सिएम रीप नाइट मार्केट",
  "Air Ticket & Visa": "हवाई टिकट और वीज़ा",
  "Bundled in the package": "पैकेज में शामिल",
  "24/7 Support": "24/7 सहायता",
  "Indian-speaking escort": "भारतीय भाषा बोलने वाला एस्कॉर्ट",
  "Secure Booking": "सुरक्षित बुकिंग",
  "Confirmed before you fly": "उड़ान से पहले कन्फ़र्म",
  "Best Price": "सबसे अच्छी कीमत",
  "Single-country focus, fair rate": "एक ही देश पर फ़ोकस, उचित दर",
  "The Plan": "योजना",
  "Three days, in order": "तीन दिन, क्रम से",
  "Every stop is arranged so you see Angkor at its best light — mornings at the great temples, evenings for rest.": "हर पड़ाव इस तरह रखा गया है कि आप अंगकोर को उसकी सबसे अच्छी रोशनी में देखें — सुबह बड़े मंदिरों में, शाम आराम के लिए।",
  "ARRIVAL": "आगमन",
  "Arrival & accommodation": "आगमन और ठहरना",
  "Land in Siem Reap and settle into your hotel. The evening opens with the sights beyond the temples — a floating village, a jungle waterfall, and dinner with a live Apsara dance.": "सिएम रीप पहुँचकर अपने होटल में ठहरें। शाम की शुरुआत मंदिरों से परे के नज़ारों से होती है — तैरता गाँव, जंगल का झरना और लाइव अप्सरा नृत्य के साथ रात्रिभोज।",
  "Dinner & Apsara Dance Show": "रात्रिभोज और अप्सरा नृत्य शो",
  "ANGKOR DAY": "अंगकोर दिवस",
  "The main Angkor circuit": "मुख्य अंगकोर सर्किट",
  "A full day through the temples Angkor is known for, before returning to the hotel for the night.": "पूरा दिन उन मंदिरों में जिनके लिए अंगकोर जाना जाता है, फिर रात के लिए होटल वापसी।",
  "Ta Prohm Temple (Tomb Raider)": "ता प्रोम मंदिर (टूम्ब रेडर)",
  "BIG CIRCLE": "बिग सर्कल",
  "The Big Circle & Banteay Srei": "बिग सर्कल और बांतेय स्रेई",
  "A wider loop out to Banteay Srei — the “Pink Temple,” 40km out — and the lesser-visited temples along the way.": "बांतेय स्रेई तक का लंबा चक्कर — 40 किमी दूर “गुलाबी मंदिर” — और रास्ते के कम भीड़ वाले मंदिर।",
  "Go Travel. Discover.": "घूमें. जानें.",
  "Cambodia, through Angkor Wat": "अंगकोर वाट के ज़रिए कंबोडिया",
  "Cambodia’s Angkor region packs a thousand years of Khmer history into a few square kilometres — temple-mountains, moated cities, and jungle ruins, all built between the 9th and 13th centuries. Angkor Wat itself began as a Hindu temple dedicated to Vishnu, a detail that still surprises most Indian travellers who visit.": "कंबोडिया का अंगकोर क्षेत्र ख्मेर इतिहास के हज़ार वर्षों को कुछ ही वर्ग किलोमीटर में समेटे हुए है — पर्वत-मंदिर, खाइयों से घिरे नगर और जंगल में छिपे खंडहर, सब 9वीं से 13वीं सदी के बीच बने। स्वयं अंगकोर वाट की शुरुआत भगवान विष्णु को समर्पित हिंदू मंदिर के रूप में हुई थी — यह बात आज भी यहाँ आने वाले ज़्यादातर भारतीय यात्रियों को चौंका देती है।",
  "This package sticks to Siem Reap and the Angkor circuit — no rushed multi-city hop — so three days is enough to see it properly.": "यह पैकेज सिएम रीप और अंगकोर सर्किट तक ही सीमित है — कई शहरों की भागदौड़ नहीं — इसलिए इसे ठीक से देखने के लिए तीन दिन काफ़ी हैं।",
  "See the tour": "टूर देखें",
  "Sites & experiences covered": "स्थल और अनुभव शामिल",
  "Days on the ground": "दिन की यात्रा",
  "Nights' stay included": "रातों का ठहराव शामिल",
  "Escort with you throughout": "एस्कॉर्ट पूरी यात्रा में साथ",
  "Travel Stories": "यात्रा की कहानियाँ",
  "Experience Angkor With Us": "हमारे साथ अंगकोर का अनुभव करें",
  "View this post on Instagram": "यह पोस्ट इंस्टाग्राम पर देखें",
  "Plan your Angkor Wat trip": "अपनी अंगकोर वाट यात्रा की योजना बनाएँ",
  "Call, WhatsApp, or write in — we’ll reply with dates and pricing.": "कॉल करें, व्हाट्सऐप करें या लिखें — हम तारीख़ों और कीमत के साथ जवाब देंगे।",
  "PHONE": "फ़ोन",
  "WHATSAPP": "व्हाट्सऐप",
  "EMAIL": "ईमेल",
  "OFFICE": "कार्यालय",
  "Your name": "आपका नाम",
  "Your phone number": "आपका फ़ोन नंबर",
  "e.g. 2": "जैसे 2",
  "Anything else we should know?": "और कुछ जो हमें जानना चाहिए?",
  "Email (optional)": "ईमेल (वैकल्पिक)",
  "Request a callback": "कॉलबैक माँगें",

  "Angkor Wat Tour, Cambodia — 2 Nights / 3 Days | AngkorIndianTrip": "अंगकोर वाट टूर, कंबोडिया — 2 रातें / 3 दिन | AngkorIndianTrip",
  "Tour Package": "टूर पैकेज",
  "Angkor Wat Tour, Cambodia": "अंगकोर वाट टूर, कंबोडिया",
  "Package Price": "पैकेज की कीमत",
  "Contact for price": "कीमत के लिए संपर्क करें",
  "+ taxes": "+ कर",
  "Duration": "अवधि",
  "2 Nights": "2 रातें",
  "/ 3 Days": "/ 3 दिन",
  "Departure City": "प्रस्थान शहर",
  "Kolkata": "कोलकाता",
  "/ (other cities on request)": "/ (अन्य शहर अनुरोध पर)",
  "Get Quote": "कोटेशन पाएँ",
  "Angkor Wat is a magnificent symbol of Cambodia’s rich heritage and architectural brilliance — and, through Lord Vishnu, carries a forgotten cultural bond with India. This 3-day Siem Reap tour covers the main Angkor circuit and the Big Circle, with air ticket, visa and an Indian-speaking escort included, so you can focus on the temples rather than the paperwork.": "अंगकोर वाट कंबोडिया की समृद्ध विरासत और अद्भुत वास्तुकला का भव्य प्रतीक है — और भगवान विष्णु के ज़रिए भारत के साथ एक भूला-बिसरा सांस्कृतिक रिश्ता भी सँजोए हुए है। 3 दिन के इस सिएम रीप टूर में मुख्य अंगकोर सर्किट और बिग सर्कल शामिल हैं, साथ ही हवाई टिकट, वीज़ा और भारतीय भाषा बोलने वाला एस्कॉर्ट भी — ताकि आपका ध्यान काग़ज़ी कार्रवाई पर नहीं, मंदिरों पर रहे।",
  "Day 1 — Arrival": "दिन 1 — आगमन",
  "Land in Siem Reap and check into your hotel. In the evening, visit a floating village and the Kulen Mountain waterfall, then close the day with dinner and a live Apsara dance show.": "सिएम रीप पहुँचकर होटल में चेक-इन करें। शाम को तैरता गाँव और कुलेन पर्वत का झरना देखें, फिर रात्रिभोज और लाइव अप्सरा नृत्य शो के साथ दिन पूरा करें।",
  "Day 2 — Angkor Day": "दिन 2 — अंगकोर दिवस",
  "A full day covering Angkor Wat Temple, Banteay Kdei, Angkor Thom City, Ta Keo Temple, and Ta Prohm (the \"Tomb Raider\" temple), before returning to the hotel for the night.": "पूरे दिन में अंगकोर वाट मंदिर, बांतेय कदेई, अंगकोर थॉम नगर, ता केओ मंदिर और ता प्रोम (\"टूम्ब रेडर\" वाला मंदिर), फिर रात के लिए होटल वापसी।",
  "Day 3 — Big Circle": "दिन 3 — बिग सर्कल",
  "Big Circle & Banteay Srei": "बिग सर्कल और बांतेय स्रेई",
  "A wider loop out to Banteay Srei, the pink sandstone temple 40km away, along with East Mebon, Preah Khan, Ta Som, Pre Rup and Neak Pean. Transfer to the airport for your flight home.": "40 किमी दूर गुलाबी बलुआ पत्थर के मंदिर बांतेय स्रेई तक का लंबा चक्कर, साथ में ईस्ट मेबोन, प्रेह खान, ता सोम, प्रे रूप और नेक पेन। इसके बाद घर की उड़ान के लिए हवाई अड्डे तक ट्रांसफ़र।",
  "Package Details": "पैकेज का विवरण",
  "Inclusions & Exclusions": "क्या शामिल है और क्या नहीं",
  "Inclusions": "शामिल",
  "Air ticket (Kolkata – Siem Reap – Kolkata)": "हवाई टिकट (कोलकाता – सिएम रीप – कोलकाता)",
  "Cambodia tourist visa": "कंबोडिया पर्यटक वीज़ा",
  "2 nights' accommodation with breakfast": "नाश्ते के साथ 2 रातों का ठहराव",
  "Return airport transfers": "हवाई अड्डे से आने-जाने का ट्रांसफ़र",
  "All sightseeing & transfers as per itinerary": "कार्यक्रम के अनुसार सभी दर्शनीय स्थल और ट्रांसफ़र",
  "Entry tickets to temples listed in the itinerary": "कार्यक्रम में दिए गए मंदिरों के प्रवेश टिकट",
  "Indian-speaking escort, 24/7 through the trip": "भारतीय भाषा बोलने वाला एस्कॉर्ट, पूरी यात्रा में 24/7",
  "Exclusions": "शामिल नहीं",
  "Meals not mentioned in the itinerary": "कार्यक्रम में न बताए गए भोजन",
  "Personal expenses & shopping": "निजी ख़र्च और ख़रीदारी",
  "Travel insurance": "यात्रा बीमा",
  "Tips & gratuities": "टिप और बख़्शीश",
  "Anything not specifically listed under Inclusions": "जो कुछ भी 'शामिल' सूची में साफ़ तौर पर नहीं दिया गया है",
  "Before You Book": "बुकिंग से पहले",
  "Cancellation & Payment Policy": "रद्दीकरण और भुगतान नीति",
  "Days before departure": "प्रस्थान से पहले के दिन",
  "Cancellation charges (per person)": "रद्दीकरण शुल्क (प्रति व्यक्ति)",
  "45 days or more": "45 दिन या उससे अधिक",
  "25% of tour cost or non-refundable component, whichever is higher": "टूर लागत का 25% या नॉन-रिफ़ंडेबल हिस्सा, जो भी अधिक हो",
  "30 – 44 days": "30 – 44 दिन",
  "50% of tour cost or non-refundable component, whichever is higher": "टूर लागत का 50% या नॉन-रिफ़ंडेबल हिस्सा, जो भी अधिक हो",
  "15 – 29 days": "15 – 29 दिन",
  "75% of tour cost or non-refundable component, whichever is higher": "टूर लागत का 75% या नॉन-रिफ़ंडेबल हिस्सा, जो भी अधिक हो",
  "Less than 15 days": "15 दिन से कम",
  "100% of tour cost": "टूर लागत का 100%",
  "Air ticket / Hotel": "हवाई टिकट / होटल",
  "100% if the ticket or room is on a non-refundable rate": "100%, यदि टिकट या कमरा नॉन-रिफ़ंडेबल दर पर है",
  "Payment stage": "भुगतान का चरण",
  "Amount due": "देय राशि",
  "At the time of booking": "बुकिंग के समय",
  "50% advance to confirm the booking": "बुकिंग कन्फ़र्म करने के लिए 50% अग्रिम",
  "30 days before departure": "प्रस्थान से 30 दिन पहले",
  "Balance 50% of the total tour cost": "कुल टूर लागत का शेष 50%",
  "Fine Print": "ज़रूरी शर्तें",
  "Terms & Conditions": "नियम और शर्तें",
  "All prices are subject to change without prior notice, based on airfare and hotel availability.": "सभी कीमतें हवाई किराए और होटल की उपलब्धता के आधार पर बिना पूर्व सूचना के बदल सकती हैं।",
  "Booking is confirmed only on receipt of advance payment.": "बुकिंग अग्रिम भुगतान मिलने पर ही कन्फ़र्म होती है।",
  "Passport copies of all travellers are required to initiate the booking and visa process.": "बुकिंग और वीज़ा प्रक्रिया शुरू करने के लिए सभी यात्रियों के पासपोर्ट की प्रतियाँ ज़रूरी हैं।",
  "Rooms and flights are subject to availability at the time of confirmation.": "कमरे और उड़ानें कन्फ़र्मेशन के समय की उपलब्धता पर निर्भर हैं।",
  "If the listed hotel is unavailable, a similar alternate property will be offered; any price difference will be communicated in advance.": "यदि सूची में दिया गया होटल उपलब्ध न हो, तो वैसा ही दूसरा होटल दिया जाएगा; कीमत में कोई अंतर हुआ तो पहले ही बता दिया जाएगा।",
  "AngkorIndianTrip is not liable for delays, cancellations, or costs arising from airline schedule changes or events beyond our control.": "एयरलाइन की समय-सारणी में बदलाव या हमारे नियंत्रण से बाहर की घटनाओं से हुई देरी, रद्दीकरण या ख़र्च के लिए AngkorIndianTrip ज़िम्मेदार नहीं है।",
  "Any expenses outside the listed inclusions are the traveller's responsibility.": "'शामिल' सूची से बाहर का कोई भी ख़र्च यात्री की ज़िम्मेदारी है।",
  "Ready to book the Angkor Wat tour?": "अंगकोर वाट टूर बुक करने के लिए तैयार हैं?",
  "Share your travel month and group size — we’ll confirm dates, pricing and visa timelines the same day.": "अपनी यात्रा का महीना और समूह का आकार बताएँ — हम उसी दिन तारीख़ें, कीमत और वीज़ा की समय-सीमा कन्फ़र्म कर देंगे।",

  "Traveller Zone — Cambodia Visa, Currency & Packing | AngkorIndianTrip": "यात्री ज़ोन — कंबोडिया वीज़ा, मुद्रा और पैकिंग | AngkorIndianTrip",
  "Everything to sort before you fly to Cambodia — visa, currency, weather, packing, and who to call if something goes wrong.": "कंबोडिया की उड़ान से पहले की हर तैयारी — वीज़ा, मुद्रा, मौसम, पैकिंग, और कुछ गड़बड़ होने पर किसे कॉल करें।",
  "Before You Fly": "उड़ान से पहले",
  "Documents & bookings to sort first": "पहले तैयार करने वाले दस्तावेज़ और बुकिंग",
  "Passport": "पासपोर्ट",
  "Valid for at least 6 months from your date of arrival in Cambodia, with two blank pages for the visa stamp.": "कंबोडिया पहुँचने की तारीख़ से कम-से-कम 6 महीने तक वैध, और वीज़ा की मुहर के लिए दो ख़ाली पन्ने।",
  "Cambodia Visa": "कंबोडिया वीज़ा",
  "Indian passport holders need a visa — most travellers apply for the e-Visa online before departure.": "भारतीय पासपोर्ट धारकों को वीज़ा चाहिए — ज़्यादातर यात्री प्रस्थान से पहले ऑनलाइन ई-वीज़ा के लिए आवेदन करते हैं।",
  "e-Visa: ~USD 30, approved in about 3 business days": "ई-वीज़ा: लगभग 30 अमेरिकी डॉलर, क़रीब 3 कार्यदिवसों में मंज़ूर",
  "Visa on arrival is also available at Siem Reap airport": "सिएम रीप हवाई अड्डे पर वीज़ा ऑन अराइवल भी उपलब्ध है",
  "Standard stay: up to 30 days": "सामान्य ठहराव: 30 दिन तक",
  "Flights & Hotel": "उड़ानें और होटल",
  "Both are booked as part of your AngkorIndianTrip package — confirmed tickets and hotel vouchers are shared before you fly.": "दोनों आपके AngkorIndianTrip पैकेज के हिस्से के रूप में बुक होते हैं — कन्फ़र्म टिकट और होटल वाउचर उड़ान से पहले साझा कर दिए जाते हैं।",
  "Travel Insurance": "यात्रा बीमा",
  "Not included in the package — we'd recommend picking up a short-trip policy before departure. Ask us and we can point you to an option.": "पैकेज में शामिल नहीं है — हमारी सलाह है कि प्रस्थान से पहले छोटी यात्रा की पॉलिसी ले लें। हमसे पूछें, हम एक विकल्प सुझा देंगे।",
  "Passport Photos & Copies": "पासपोर्ट फ़ोटो और प्रतियाँ",
  "Carry 2 passport-size photos and photocopies of your passport's first two pages, separate from the original.": "2 पासपोर्ट साइज़ फ़ोटो और पासपोर्ट के पहले दो पन्नों की फ़ोटोकॉपी साथ रखें, मूल पासपोर्ट से अलग।",
  "Save Our Number": "हमारा नंबर सेव करें",
  "Your escort's contact and our 24/7 support line are shared before departure — save them to your phone before you fly.": "आपके एस्कॉर्ट का नंबर और हमारी 24/7 सहायता लाइन प्रस्थान से पहले साझा की जाती है — उड़ान से पहले इन्हें अपने फ़ोन में सेव कर लें।",
  "Good To Know": "जानने योग्य बातें",
  "Cambodia at a glance": "एक नज़र में कंबोडिया",
  "Currency": "मुद्रा",
  "The Cambodian Riel (KHR) is the official currency, but US Dollars are accepted almost everywhere in Siem Reap — carry small USD notes for temple entries and tips.": "कंबोडियाई रियल (KHR) आधिकारिक मुद्रा है, लेकिन सिएम रीप में लगभग हर जगह अमेरिकी डॉलर चलते हैं — मंदिर प्रवेश और टिप के लिए छोटे डॉलर नोट साथ रखें।",
  "Best Time to Visit": "घूमने का सबसे अच्छा समय",
  "November to March is the dry, cooler season and the most comfortable time to explore the temples. April–May is hot; June–October is the rainy season.": "नवंबर से मार्च सूखा और ठंडा मौसम होता है, और मंदिर घूमने का सबसे आरामदायक समय। अप्रैल–मई में गर्मी रहती है; जून–अक्टूबर बरसात का मौसम है।",
  "What to Pack": "क्या पैक करें",
  "Light, breathable clothing, a hat and sunscreen, comfortable walking shoes, and shoulders/knees covered for temple visits.": "हल्के, हवादार कपड़े, टोपी और सनस्क्रीन, चलने के लिए आरामदायक जूते, और मंदिर दर्शन के लिए कंधे व घुटने ढकने वाले कपड़े।",
  "Time Zone & Language": "समय क्षेत्र और भाषा",
  "Cambodia is on ICT (UTC+7), an hour and a half ahead of India. Khmer is the official language; English is widely understood around Siem Reap's tourist areas.": "कंबोडिया ICT (UTC+7) पर चलता है, भारत से डेढ़ घंटा आगे। ख्मेर आधिकारिक भाषा है; सिएम रीप के पर्यटन क्षेत्रों में अंग्रेज़ी आम तौर पर समझी जाती है।",
  "Electricity": "बिजली",
  "230V, mostly Type A/C/G sockets. Carry a universal adapter — Indian 3-pin plugs don't always fit.": "230V, ज़्यादातर टाइप A/C/G सॉकेट। यूनिवर्सल अडैप्टर साथ रखें — भारतीय 3-पिन प्लग हर जगह नहीं लगते।",
  "SIM & Connectivity": "सिम और कनेक्टिविटी",
  "Local prepaid SIMs are available at Siem Reap airport, or activate an international roaming pack before you leave India.": "सिएम रीप हवाई अड्डे पर स्थानीय प्रीपेड सिम मिल जाते हैं, या भारत छोड़ने से पहले इंटरनेशनल रोमिंग पैक चालू करा लें।",
  "Just In Case": "ज़रूरत पड़ने पर",
  "Emergency contacts in Cambodia": "कंबोडिया में आपातकालीन संपर्क",
  "Service": "सेवा",
  "Number": "नंबर",
  "Police (national)": "पुलिस (राष्ट्रीय)",
  "Fire (national)": "अग्निशमन (राष्ट्रीय)",
  "Ambulance (national)": "एम्बुलेंस (राष्ट्रीय)",
  "Siem Reap Tourist Police": "सिएम रीप पर्यटक पुलिस",
  "AngkorIndianTrip 24/7 Support": "AngkorIndianTrip 24/7 सहायता",
  "Your escort is reachable throughout the trip — for most situations, call them first.": "आपका एस्कॉर्ट पूरी यात्रा में उपलब्ध रहता है — ज़्यादातर स्थितियों में पहले उन्हें ही कॉल करें।",
  "Questions before you book?": "बुकिंग से पहले कोई सवाल?",
  "Visa, packing, or anything else about the trip — call, WhatsApp, or send an enquiry and we’ll walk you through it.": "वीज़ा, पैकिंग या यात्रा से जुड़ी कोई भी बात — कॉल करें, व्हाट्सऐप करें या पूछताछ भेजें, हम आपको सब समझा देंगे।",
  "Talk to Us": "हमसे बात करें"
};
